# Generated by Django 5.1 on 2024-08-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_processo', models.CharField(max_length=50, unique=True)),
                ('classe', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('data_de_distribuicao', models.DateField()),
                ('juiz', models.CharField(max_length=150)),
                ('valor_da_acao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParteProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_parte', to='desafio.parte')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo_parte', to='desafio.processo')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('movimento', models.CharField(max_length=2000)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='desafio.processo')),
            ],
        ),
    ]
