# Generated by Django 5.1 on 2024-08-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parteprocesso',
            name='parte',
        ),
        migrations.RemoveField(
            model_name='parteprocesso',
            name='processo',
        ),
        migrations.DeleteModel(
            name='Movimentacao',
        ),
        migrations.DeleteModel(
            name='Parte',
        ),
        migrations.DeleteModel(
            name='ParteProcesso',
        ),
        migrations.DeleteModel(
            name='Processo',
        ),
    ]
