# Generated by Django 5.1 on 2024-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desafio', '0002_remove_parteprocesso_parte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_do_processo', models.CharField(max_length=50, unique=True)),
                ('classe', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('assunto', models.CharField(max_length=100)),
                ('data_de_distribuicao', models.DateField()),
                ('juiz', models.CharField(max_length=150)),
                ('valor_da_acao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
