# Generated by Django 5.1 on 2024-08-19 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='numero_do_processo',
            new_name='numero',
        ),
    ]
