# Generated by Django 5.1 on 2024-08-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0004_rename_numero_do_processo_processo_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='numero',
            new_name='numero_do_processo',
        ),
    ]
