# Generated by Django 5.1 on 2024-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_processo_grau_alter_processo_numero_do_processo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='movimentacoes',
            field=models.TextField(default='Nenhuma ação encontrada'),
        ),
    ]
