# Generated by Django 5.1 on 2024-08-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0007_processo_movimentacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='valor_da_acao',
        ),
    ]
